---
# tasks file for ssl
- name: Install software-properties-common
  apt: name=software-properties-common state=present
  become: yes
- name: add ppa
  apt_repository: repo='ppa:certbot/certbot'
  become: yes
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes
- name: Install Certbot
  apt: name=python-certbot-apache state=present
  become: yes
- name: Certificate
  command: certbot --apache --email {{ email }} -d {{ site }}
  become: yes
